server:
  port: 8080
spring:
  application:
    name: game-service
  datasource:
    url: jdbc:h2:mem:game-service
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
player-service:
  host: localhost
  port: 8081
  entryPoint: player